<?php
/**
 * Trevor Kamin
 * CIS 222 Project 1
 *
 * This website was used as my PHP w/ MYSQL course with professor Banks. It will
 *be used in a production for Fancie That Candles. This is a complete online
 * store, and will be fully functional when completed.
 *
 * PHP version 5.4.45
 *
 * @package    Fancie That Candles
 * @author     Trevor Kamin
 * @copyright  2018 Fancie That Candles
 * @version    12/09/2018
 * @link       https://cislinux.hfcc.edu/~tkamin/project2/index.php
 */

// The mysqli part 
require ('../../creds.php');
require ('../../creds2.php');


 $dbc = @mysqli_connect (DB_HOST,DB_USER,DB_PASSWORD,DB_NAME) OR die ('Could not conect to Mysql:
         MySql: ' . mysqli_connect_error() );

mysqli_set_charset($dbc, 'utf8');		 