<?php
/**
 * Trevor Kamin
 * CIS 222 Project 1
 *
 * This website was used as my PHP w/ MYSQL course with professor Banks. It will
 *be used in a production for Fancie That Candles. This is a complete online
 * store, and will be fully functional when completed.
 *
 * PHP version 5.4.45
 *
 * @package    Fancie That Candles
 * @author     Trevor Kamin
 * @copyright  2018 Fancie That Candles
 * @version    12/09/2018
 * @link       https://cislinux.hfcc.edu/~tkamin/project2/index.php
 */
?>

<!DOCTYPE html>
<!-- The header which determines which links to show based upon your cookies -->
<html>
    <head>
	      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width">
      <link rel="stylesheet" href="styles/main.css">
        <title>Fancie That Candles</title>
    </head>
    <body>
	      <div class="maincontain">
      <div class="header-nav-container">
         <p class="skipnavigation"><a href="contentstart">Skip navigation</a></p>
         <header>
		 <h1>Fancie That Candles</h1>
            <div class="img">
               <a href="index.php"><img src="images/logo.jpg" alt="flower"></a>
            </div>
         </header>
         <nav class="sitenavigation">
            <ul>
			<?php
			if (!isset($_SESSION['userSignedIn']) || !$_SESSION['userSignedIn']) {
              echo "<li><a href=\"index.php?page=home\">Home</a></li>
               <li><a href=\"index.php?page=products\">Products</a></li>
               <li><a href=\"index.php?page=contact\">Contact Us</a></li>
               <li><a href=\"index.php?page=signup\">Sign Up</a></li>
                <li><a href=\"index.php?page=login\">Login</a></li>";
			}
			else if(isset($_SESSION['userSignedIn']) || $_SESSION['userSignedIn']){
				echo "<li><a href=\"index.php?page=home\">Home</a></li>
               <li><a href=\"index.php?page=products\">Products</a></li>
               <li><a href=\"index.php?page=contact\">Contact Us</a></li>
			   <li><a href=\"index.php?page=cart\">View Cart</a></li>
			   <form method='post'>
			   <input type='hidden' name='action' value='signout'>
			    <input type='submit' name='submit' value='logout'></li>
			    </form>";

			}

				?>
            </ul>
         </nav>
      </div>
    <hr>