<?php
/**
 * Trevor Kamin
 * CIS 222 Project 1
 *
 * This website was used as my PHP w/ MYSQL course with professor Banks. It will
 *be used in a production for Fancie That Candles. This is a complete online
 * store, and will be fully functional when completed.
 *
 * PHP version 5.4.45
 *
 * @package    Fancie That Candles
 * @author     Trevor Kamin
 * @copyright  2018 Fancie That Candles
 * @version    12/09/2018
 * @link       https://cislinux.hfcc.edu/~tkamin/project2/index.php
 */
?>

<!-- The about us include -->
 <h1>Fancie That Candles</h1>
 <form action="index.php?page=search" method="post">
 <fieldset align="center"> <legend align="center">Search Products: </legend>
 <p align="center"><input type="text" name="search_prod" placeholder="Search"></p>
 <p align="center"><input type="submit" name="submit" value="Search"></p>
</fieldset>
</form>
<div class="center">
    <p align="center">
        A little about us.  We wanted to create a way to to enjoy candles in a more natural sense.<br>
        Our business is based on trying to keep everything as natural as possible!  I am always<br>
        looking for healthier options for my family in just about everything.  So when we started<br>
        thinking about what we burn in our homes to make them smell nice, I also started thinking<br>
        about all the chemicals we were releasing into our air.  Sometimes, this is often overlooked <br>
        in the simple things like burning candles in our homes.  We worry about what we are eating,<br>
        but not so much what we are breathing in. So, we started making soy candles.<br><br>

        I’m really proud to say that our candles are all natural soy, dye-free and made with natural<br>
        wicks.  We use only high quality, un-cut pure fragrance oils in our candles. They are clean<br>
        burning which means no toxins or carcinogens and are less likely to trigger allergies.  Soy<br>
        is biodegradable and the soy we purchase to hand pour our candles, is farmed right here in the<br>
        U.S.  So not only are our candles better for our health and the environment, we are also helping<br>
        to support our American farmers!  Soy will burn 35-50% longer than paraffin candles, as well as<br>
        have a better, cleaner and stronger scent.  The bonus with soy is easy clean up!  Just a little<br>
        soap and water!<br><br>

        Our candles are all hand poured for individual orders. So each and every order placed is made<br>
        especially for you! Proudly made right here in the Michigan Mitten.
    </p>
</div>

</html>
 