<?php
/**
 * Trevor Kamin
 * CIS 222 Project 1
 *
 * This website was used as my PHP w/ MYSQL course with professor Banks. It will
 *be used in a production for Fancie That Candles. This is a complete online
 * store, and will be fully functional when completed.
 *
 * PHP version 5.4.45
 *
 * @package    Fancie That Candles
 * @author     Trevor Kamin
 * @copyright  2018 Fancie That Candles
 * @version    12/09/2018
 * @link       https://cislinux.hfcc.edu/~tkamin/project2/index.php
 */

// This page prints any errors associated with logging in
// and it creates the entire login page, including the form.
// Include the header:
$page_title = 'Login';
?>

<hr>
<div class="Login">
<fieldset><legend align="center">Login:</legend>
<form  method="post">
    <input type="hidden" name="action" value="login">
	<p align="center">Email Address: <input type="text" name="email" size="20" maxlength="60" /> </p>
	<p align="center">Password: <input type="password" name="pass" size="20" maxlength="20" /></p>
	<p align="center"><input type="submit" name="submit"/></p>
</fieldset>
</form>
</div>
<hr>
