<?php
/**
 * Trevor Kamin
 * CIS 222 Project 1
 *
 * This website was used as my PHP w/ MYSQL course with professor Banks. It will
 *be used in a production for Fancie That Candles. This is a complete online
 * store, and will be fully functional when completed.
 *
 * PHP version 5.4.45
 *
 * @package    Fancie That Candles
 * @author     Trevor Kamin
 * @copyright  2018 Fancie That Candles
 * @version    12/09/2018
 * @link       https://cislinux.hfcc.edu/~tkamin/project2/index.php
 */
?>

<h2>Sign In</h2>

<form action="index.php" method="POST" >
    <label for="email" >Email:</label>
    <input type="text" name="email" >
    <br>

    <label for="password" >Password:</label>
    <input type="text" name="password" >

    <br>

    <input type="hidden" name="action" value="signin" >
    <input type="submit" value="Submit" >
</form>